KEY_OVERRIDE_ENABLE = yes
LAYER_LOCK_ENABLE = no
# CAPS_WORD_ENABLE = yes # 3416 bytes free vs 3846 with custom implementation
# COMBO_ENABLE = yes
# REPEAT_KEY_ENABLE = yes

RGBLIGHT_ENABLE = no
RGBLIGHT_ANIMATIONS = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MUSIC_ENABLE = no

LTO_ENABLE = yes
EXTRAFLAGS += -flto
